### ISSUE TITLE
make nodejs start automatically

### ISSUE THREAD

**Issue by ingomueller-net** [AEGEE/oms-development-vm#10] opened 2015-11-08 12:42 UTC
A good thing is that literally the developer is ready to do stuff with the API. 

The downside is that during the API phase, the core will need to be restarted several times in order to integrate the new features.

----------------------------------------
- Bitbucket: https://bitbucket.org/ingomueller-net/ldap-poc/issue/10
- Originally reported by: [grasshopper](http://bitbucket.org/grasshopper)
- Originally created at: 2015-06-02T11:11:11.139

**Comment by ingomueller-net** [comment] 2015-11-08 12:42
As per my second comment, this is on hold until we can say the core is finished

----------------------------------------
Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by serviceman** [comment] 2015-11-08 15:40
for some reason this was duplicate of #11

**Closed by serviceman** 2015-11-08 15:40 UTC
